# Generated by Django 2.2.7 on 2020-07-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('role', models.CharField(blank=True, max_length=25)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
